# Generated by Django 4.1.7 on 2023-03-15 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=100)),
                ('spanish_name', models.CharField(max_length=100)),
            ],
        ),
    ]
