# Generated by Django 4.1.7 on 2023-04-06 21:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storytopic',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='storytopic',
            name='spanish_name',
        ),
        migrations.AddField(
            model_name='storytopic',
            name='language',
            field=models.IntegerField(choices=[(0, 'English'), (1, 'Spanish')], default=0),
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=256)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='phrases.storytopic')),
            ],
        ),
    ]
