# Generated by Django 4.1.7 on 2023-03-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryTopic',
        ),
    ]
